import { motion } from 'framer-motion';
import { Link } from 'react-router-dom';
import { ArrowRight, CheckCircle2, Globe2 } from 'lucide-react';
import { cfsSteps, services, whyChoose } from '../data/site';

export const fade = { initial:{opacity:0,y:24}, whileInView:{opacity:1,y:0}, viewport:{once:true}, transition:{duration:.6} };
export function SectionTitle({eyebrow,title,text}:{eyebrow:string;title:string;text?:string}){return <motion.div {...fade} className="mx-auto mb-12 max-w-3xl text-center"><p className="font-extrabold uppercase tracking-widest text-[#FF8A00]">{eyebrow}</p><h2 className="mt-3 text-3xl md:text-5xl font-black text-[#0B2D5B]">{title}</h2>{text&&<p className="mt-4 text-lg text-slate-600">{text}</p>}</motion.div>}
export function ServiceCards(){return <div className="grid gap-6 md:grid-cols-2 lg:grid-cols-4">{services.map((s,i)=>{const Icon=s.icon;return <motion.article {...fade} transition={{duration:.5,delay:i*.05}} className="card p-6 hover:-translate-y-2 transition" key={s.title}><div className="mb-5 grid h-14 w-14 place-items-center rounded-2xl bg-blue-50 text-[#0B2D5B]"><Icon size={28}/></div><h3 className="text-xl font-black text-[#0B2D5B]">{s.title}</h3><p className="mt-3 text-slate-600">{s.text}</p><Link to="/contact" className="mt-5 inline-flex items-center gap-2 font-bold text-[#FF8A00]">Learn More <ArrowRight size={16}/></Link></motion.article>})}</div>}
export function WhyChoose(){return <div className="grid gap-5 md:grid-cols-2 lg:grid-cols-3">{whyChoose.map(([t,d,Icon]:any,i)=><motion.div {...fade} transition={{duration:.5,delay:i*.03}} className="card p-6" key={t}><Icon className="text-[#FF8A00]"/><h3 className="mt-4 font-black text-xl text-[#0B2D5B]">{t}</h3><p className="mt-2 text-slate-600">{d}</p></motion.div>)}</div>}
export function CFSTimeline(){return <div className="grid gap-4 md:grid-cols-2 lg:grid-cols-5">{cfsSteps.map((step,i)=><motion.div {...fade} transition={{delay:i*.04}} className="card p-5" key={step}><span className="text-sm font-black text-[#FF8A00]">{String(i+1).padStart(2,'0')}</span><h3 className="mt-2 font-black text-[#0B2D5B]">{step}</h3></motion.div>)}</div>}
export function Values(){const vals=['Customer Commitment','Quality','Integrity','Teamwork','Personal Accountability'];return <div className="grid gap-5 md:grid-cols-5">{vals.map(v=><div className="card p-5 text-center" key={v}><CheckCircle2 className="mx-auto text-[#FF8A00]"/><h3 className="mt-3 font-black text-[#0B2D5B]">{v}</h3><p className="mt-2 text-sm text-slate-600">Reliable standards, transparent work, and ownership in every commitment.</p></div>)}</div>}
export function WorldMapVisual(){return <div className="relative overflow-hidden rounded-[2rem] border border-blue-100 bg-blue-50 map-grid p-8 min-h-[320px]"><Globe2 className="absolute right-8 top-8 text-[#0B2D5B] opacity-20" size={150}/><div className="relative z-10 max-w-md"><p className="text-[#FF8A00] font-black uppercase tracking-widest">Worldwide Connectivity</p><h3 className="mt-3 text-3xl font-black text-[#0B2D5B]">Connecting cargo across global trade routes</h3><p className="mt-4 text-slate-600">Global partners, regional expertise, and reliable end-to-end coordination for international shipments.</p></div><div className="absolute bottom-10 left-12 right-12 h-1 bg-gradient-to-r from-[#0B2D5B] via-[#FF8A00] to-blue-500 rounded-full"/></div>}
